# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: any1's logs
email: ''

#write html inside the double quotes to display in jumbotron
description: "<h1>any1's logs</h1>"



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://any1one.github.io" # the base hostname & protocol for your site
twitter_username: any1ops
github_username:  any1one

# Build settings
markdown: kramdown
permalink: :categories/:year-:month-:day-:title:output_ext
